name       : rpcbind
version    : 0.2.4
release    : 3
source     :
    - https://iweb.dl.sourceforge.net/project/rpcbind/rpcbind/0.2.4/rpcbind-0.2.4.tar.bz2 : 074a9a530dc7c11e0d905aa59bcb0847c009313f02e98d3d798aa9568f414c66
license    : BSD-3-Clause
component  : system.utils
summary    : rpcbind is a server that converts RPC program numbers into universal addresses.
description: |
    rpcbind is a server that converts RPC program numbers into universal addresses.
builddeps  :
    - pkgconfig(libtirpc)
setup      : |
    %patch -p1 < $pkgfiles/security/CVE-2017-8779.patch
    %configure --enable-warmstarts
build      : |
    %make
install    : |
    %make_install
