name       : rpcbind
version    : 1.2.6
release    : 4
source     :
    - https://deac-fra.dl.sourceforge.net/project/rpcbind/rpcbind/1.2.6/rpcbind-1.2.6.tar.bz2 : 5613746489cae5ae23a443bb85c05a11741a5f12c8f55d2bb5e83b9defeee8de
license    : BSD-3-Clause
component  : system.utils
summary    : rpcbind is a server that converts RPC program numbers into universal addresses.
description: |
    rpcbind is a server that converts RPC program numbers into universal addresses.
builddeps  :
    - pkgconfig(libtirpc)
    - rpcsvc-proto-devel
setup      : |
    %patch -p1 < $pkgfiles/security/CVE-2017-8779.patch
    %configure --enable-warmstarts
build      : |
    %make
install    : |
    %make_install
